/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/lastModelfinal2.gltf')
  const { actions } = useAnimations(animations, group);
  const [name, setName] = useState('');
  useEffect(() => {
    if(props.name==="welcome"){
      actions.AYUBOWAN.play();
      setName(props.name);
    }
    if(props.name==="thanks"){
      actions.thanks_metarig.play();
      setName(props.name);
    }
    
  }, [props.name])
  setTimeout(
    () => {if(props.name==="welcome"){
      actions.AYUBOWAN.stop();
      setName('');
    }
    if(props.name==="thanks"){
      actions.thanks_metarig.stop();
      setName('');
    }
    else{
      setName('');
    }}, 
    4000
  );

  return (
    <group ref={group} {...props} dispose={null}>
    {console.log(useGLTF('/lastModelfinal2.gltf'))}
    {console.log(actions)}
      <group position={[-0.65, -0.48, 0]}>
        <group position={[0.64, -0.54, -0.48]} scale={[0.97, 0.97, 0.97]}>
          <primitive object={nodes.spine} />
          <skinnedMesh
            material={materials['Material.002']}
            geometry={nodes.Boy_body_ply.geometry}
            skeleton={nodes.Boy_body_ply.skeleton}
          />
          <skinnedMesh
            material={materials['Material.001']}
            geometry={nodes.Boy_hair_ply.geometry}
            skeleton={nodes.Boy_hair_ply.skeleton}
          />
          <skinnedMesh
            material={materials['Material.011']}
            geometry={nodes.Boy_jacket_ply.geometry}
            skeleton={nodes.Boy_jacket_ply.skeleton}
          />
          <skinnedMesh
            material={materials['Material.003']}
            geometry={nodes.Boy_pants_ply.geometry}
            skeleton={nodes.Boy_pants_ply.skeleton}
          />
          <skinnedMesh
            material={materials.Material_0}
            geometry={nodes.Boy_shoeLft_ply.geometry}
            skeleton={nodes.Boy_shoeLft_ply.skeleton}
          />
          <skinnedMesh
            material={materials.Material_0}
            geometry={nodes.Boy_shoeRgt_ply.geometry}
            skeleton={nodes.Boy_shoeRgt_ply.skeleton}
          />
          <skinnedMesh
            material={materials.Material_0}
            geometry={nodes.Boy_tongue_ply.geometry}
            skeleton={nodes.Boy_tongue_ply.skeleton}
          />
        </group>
      </group>
      <mesh
        material={materials['Material.004']}
        geometry={nodes.Sphere.geometry}
        position={[-0.03, 0.79, -0.37]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        material={materials['Material.007']}
        geometry={nodes.Sphere001.geometry}
        position={[0.03, 0.79, -0.37]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        material={materials['Material.005']}
        geometry={nodes.Sphere002.geometry}
        position={[-0.04, 0.79, -0.33]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        material={materials['Material.006']}
        geometry={nodes.Sphere003.geometry}
        position={[0.04, 0.79, -0.33]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  )
}

useGLTF.preload('/lastModelfinal2.gltf')
